import { useMemo, useRef, useState } from 'react';
import * as Location from 'expo-location';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import MapView, { Marker, Polygon, Region } from 'react-native-maps';
import { router } from 'expo-router';
import type { Plot, Reading } from '@/types/domain';
import { getPlotStatus, STATUS_COLORS, STATUS_LABELS } from '@/utils/plotStatus';

export default function PlotMap({ plots, readings, organizationName }: { plots: Plot[]; readings: Record<string, Reading | null>; organizationName?: string }) {
  const mapRef = useRef<MapView | null>(null); const [locationEnabled, setLocationEnabled] = useState(false);
  const region = useMemo<Region>(() => ({ latitude: -31.37, longitude: -58.01, latitudeDelta: .04, longitudeDelta: .04 }), []);
  async function goToLocation() { try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted' || !(await Location.hasServicesEnabledAsync())) { setLocationEnabled(false); return; } const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setLocationEnabled(true); mapRef.current?.animateToRegion({ latitude: current.coords.latitude, longitude: current.coords.longitude, latitudeDelta: .01, longitudeDelta: .01 }, 500); } catch { setLocationEnabled(false); } }
  return <View style={styles.page}><View style={styles.header}><Text style={styles.title}>Mapa de lotes</Text><Text style={styles.org}>{organizationName}</Text></View><MapView ref={mapRef} style={styles.map} initialRegion={region} showsUserLocation={locationEnabled}>{plots.map(plot => { const status = getPlotStatus(readings[plot.id], plot.threshold_min, plot.threshold_max); const ring = plot.polygon.coordinates[0] ?? []; const coords = ring.map(pair => ({ latitude: pair[1] ?? 0, longitude: pair[0] ?? 0 })); const center = coords[0] ?? { latitude: -31.37, longitude: -58.01 }; return <View key={plot.id}><Polygon coordinates={coords} fillColor={`${STATUS_COLORS[status]}55`} strokeColor={STATUS_COLORS[status]} strokeWidth={2} tappable onPress={() => router.push(`/plot/${plot.id}`)} /><Marker coordinate={center} title={plot.name} description={STATUS_LABELS[status]} onCalloutPress={() => router.push(`/plot/${plot.id}`)} /></View>; })}</MapView><ScrollView horizontal style={styles.legend}>{(['stale', 'dry', 'optimal', 'wet'] as const).map(status => <View key={status} style={styles.legendItem}><View style={[styles.dot, { backgroundColor: STATUS_COLORS[status] }]} /><Text>{STATUS_LABELS[status]}</Text></View>)}</ScrollView><Pressable style={styles.location} onPress={() => { void goToLocation(); }}><Text>⌖ {locationEnabled ? 'Ubicación centrada' : 'Mi ubicación'}</Text></Pressable></View>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, header: { padding: 16, backgroundColor: '#F5F7F2' }, title: { fontSize: 24, fontWeight: '800', color: '#14532D' }, org: { color: '#64748B', marginTop: 3 }, map: { flex: 1 }, legend: { maxHeight: 48, padding: 10, backgroundColor: 'white' }, legendItem: { flexDirection: 'row', alignItems: 'center', marginRight: 15, gap: 5 }, dot: { width: 12, height: 12, borderRadius: 6 }, location: { position: 'absolute', right: 16, bottom: 70, padding: 14, borderRadius: 25, backgroundColor: 'white', elevation: 3 } });
